---
title: "Aggregate Data"
author: "Mac Prible"
date: "2024-11-06"
output: html_document
---

# Import Data
```{r, warning=FALSE, message=FALSE}
library(tidyverse)

tidy_data_directory <- "C:\\Users\\Mac Prible\\OneDrive - The University of Texas at Austin\\research\\PDSV\\data\\dissertation\\v3d\\tidy_output"

figure_directory <- "C:\\Users\\Mac Prible\\OneDrive - The University of Texas at Austin\\research\\PDSV\\data\\dissertation\\figures"

mean_across_stance <- 
  list.files(tidy_data_directory, pattern="*_mean_across_stance.csv") %>% 
  map_df(~read_csv2(file.path(tidy_data_directory,.)))
  
step_lengths <- 
  list.files(tidy_data_directory, pattern="*_step_lengths.csv") %>% 
  map_df(~read_csv2(file.path(tidy_data_directory,.)))
```

## Get Stance Times
```{r}
stance_times <- mean_across_stance %>% 
  filter(variable %in% c("TIME") & axis == "X") %>% 
  group_by(subject, condition, period, stance_side, normalized_time) %>% 
  summarize(time = mean(value)) %>% 
  ungroup() %>% 
  group_by(subject, condition, period, stance_side) %>%   
  summarize(start_stance = min(time),
            stop_stance = max(time)) %>% 
  ungroup() %>% 
  mutate(stance_time = stop_stance - start_stance)

```

## Define Conditions

```{r}
UNI_CONDITION_LABELS <- c(
  "sbt" = "Conventional SBT",
  "ubp" = "Uni. Fast Brake",
  "upp" = "Uni. Fast Prop"
)

BIL_CONDITION_LABELS <- c(
  "bbp" = "Bil. Fast Brake",
  "bpp" = "Bil. Fast Prop"
)
```


# Step Length Ratio (SLR)

## All time periods.

```{r}
primary_periods <- c("Late Baseline", "Early Adapt" , "Late Adapt", "Early Post Adapt")
 
plt_SLR <- step_lengths %>% 
  filter(period %in% primary_periods) %>% 
  filter(condition %in% names(UNI_CONDITION_LABELS)) %>% 
  mutate(condition = UNI_CONDITION_LABELS[condition]) %>% 
  mutate(period = factor(period, levels = primary_periods)) %>% 
  group_by(subject, condition, period, stance_side) %>% 
  summarize(step_length = mean(step_length)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = stance_side, values_from = step_length, names_glue = "{stance_side}_step_length") %>% 
  mutate(SLR = left_step_length/right_step_length) %>% 
  ggplot(aes(x=period, y = SLR, group = subject, color=subject))+
  geom_point()+
  geom_line()+
  geom_hline(yintercept =1, linetype="dashed")+
  facet_grid(cols=vars(condition))+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5,),
        plot.caption = element_text(hjust = 0.5, size = 13),
        axis.text.x = element_text(angle = 45, hjust = 1),   # Add this line
        legend.position = "bottom")+
  labs(title = "SLR Across Treadmill Protocol")

plt_SLR

ggsave(file.path(figure_directory,"SLR_all.png"))
plt_SLR +
  stat_summary(aes(group = 1), fun = mean, geom = "line", color = "black", size = 0.8, linetype = "dashed", alpha=.6) +  # Thinner, dashed mean line
  stat_summary(aes(group = 1), fun = mean, geom = "point", color = "black", size = 3, shape = 18) +  # Smaller mean points
  geom_text(stat = "summary", fun = mean,
            aes(label = sprintf("%.2f", ..y..), group = 1,
                # hjust = ifelse(period %in% c("Baseline"), 1.5, -1)
                ),
            color = "black", vjust = -0.5, size = 4, fontface = "bold",
            bg.color = "white", bg.r = 0.15)

ggsave(file.path(figure_directory,"SLR_all_w_mean.png"))

```
## Late Baseline vs Early Post Adaptation

```{r}

primary_periods <- c("Late Baseline", "Early Post Adapt")
 
plt_SLR <- step_lengths %>% 
  filter(period %in% primary_periods) %>% 
  filter(condition %in% names(UNI_CONDITION_LABELS)) %>% 
  mutate(condition = CONDITION_LABELS[condition]) %>% 
  mutate(period = factor(period, levels = primary_periods)) %>% 
  group_by(subject, condition, period, stance_side) %>% 
  summarize(step_length = mean(step_length)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = stance_side, values_from = step_length, names_glue = "{stance_side}_step_length") %>% 
  mutate(SLR = left_step_length/right_step_length) %>% 
  ggplot(aes(x=period, y = SLR, group = subject, color=subject))+
  geom_point()+
  geom_line()+
  geom_hline(yintercept =1, linetype="dashed")+
  facet_grid(cols=vars(condition))+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5,),
        plot.caption = element_text(hjust = 0.5, size = 13),
        axis.text.x = element_text(angle = 45, hjust = 1),   # Add this line
        legend.position = "bottom")+
  labs(title = "SLR Across Treadmill Protocol")

plt_SLR

ggsave(file.path(figure_directory,"SLR_pre_post.png"))
plt_SLR +
  stat_summary(aes(group = 1), fun = mean, geom = "line", color = "black", size = 0.8, linetype = "dashed", alpha=.6) +  # Thinner, dashed mean line
  stat_summary(aes(group = 1), fun = mean, geom = "point", color = "black", size = 3, shape = 18) +  # Smaller mean points
  geom_text(stat = "summary", fun = mean,
            aes(label = sprintf("%.2f", ..y..), group = 1,
                # hjust = ifelse(period %in% c("Baseline"), 1.5, -1)
                ),
            color = "black", vjust = -0.5, size = 4, fontface = "bold",
            bg.color = "white", bg.r = 0.15)

ggsave(file.path(figure_directory,"SLR_pre_post_mean.png"))

```


# Ankle PF Torque

## By Subject
```{r, fig.width=10, fig.height=6}
periods = c("Late Baseline", "Early Post Adapt")
mean_across_stance %>% 
  filter(period %in% periods) %>% 
  mutate(period = factor(period,levels = periods)) %>% 
  filter(variable %in% c("IPSI_ANKLE_MOMENT") & axis == "X") %>% 
  ggplot(aes(x=normalized_time,y= value, linetype=period, color=condition))+
  geom_line()+
  geom_hline(yintercept = 0)+
  scale_x_continuous(labels=NULL)+
  facet_grid(subject~condition + stance_side)+
  scale_linetype_manual(values=c("Early Post Adapt"="solid", "Late Baseline"="dashed")) +
  theme_minimal()+
  theme(legend.position="bottom")+
  labs(
    x = "Normalized Stance Time (0-100%)",
    y = "Ankle PF Torque (N.m/BW)",
    title = "Ankle Torque Across Conditions",
    subtitle = "Averaged Across 5 Steps",
    color = "Condition"
  )


```

## Characteristic Torque Profile
### Study 2: Unilateral


```{r, fig.height=10, fig.width=8}

mean_across_stance %>% 
  filter(period %in% periods) %>% 
  mutate(period = factor(period,levels = periods)) %>% 
  filter(condition %in% names(UNI_CONDITION_LABELS)) %>%  
  mutate(condition = UNI_CONDITION_LABELS[condition]) %>% 
  filter(variable %in% c("IPSI_ANKLE_MOMENT") & axis == "X") %>% 
  group_by(period, condition, variable, normalized_time, stance_side) %>% 
  summarize(
    PF_torque = mean(value),
    se = sd(value)/sqrt(n()),  # Standard error
    ci = 1.96 * se,            # 95% confidence interval
    upper = PF_torque + ci,
    lower = PF_torque - ci,
    .groups = 'drop'
  ) %>% 
  ggplot(aes(x = normalized_time, color = condition, linetype = period)) +
  geom_ribbon(aes(
    ymin = lower, 
    ymax = upper,
    fill = condition,
    group = interaction(condition, period)
  ), 
  alpha = 0.2,
  color = NA
  ) +
  geom_line(aes(y = PF_torque), size = 1) +
  geom_hline(yintercept = 0) +
  scale_x_continuous(labels = NULL) +
  facet_grid(
    rows = vars(condition),
    cols = vars(stance_side)
  ) +
  scale_linetype_manual(values = c("Early Post Adapt" = "solid", "Late Baseline" = "dashed")) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(
    x = "Normalized Stance Time (0-100%)",
    y = "Ankle PF Torque (N.m/BW)",
    title = "Ankle Torque Across Conditions",
    subtitle = "Averaged Across Subjects (95% CI)",
    color = "Condition",
    fill = "Condition"
  )


ggsave(file.path(figure_directory,"unil_torque_over_time.png"))
```


### Study 3: Bilateral 


```{r, fig.height=7, fig.width=8}

mean_across_stance %>% 
  filter(period %in% periods) %>% 
  mutate(period = factor(period,levels = periods)) %>% 
  filter(condition %in% names(BIL_CONDITION_LABELS)) %>%  
  mutate(condition = BIL_CONDITION_LABELS[condition]) %>% 
  filter(variable %in% c("IPSI_ANKLE_MOMENT") & axis == "X") %>% 
  group_by(period, condition, variable, normalized_time, stance_side) %>% 
  summarize(
    PF_torque = mean(value),
    se = sd(value)/sqrt(n()),  # Standard error
    ci = 1.96 * se,            # 95% confidence interval
    upper = PF_torque + ci,
    lower = PF_torque - ci,
    .groups = 'drop'
  ) %>% 
  ggplot(aes(x = normalized_time, color = condition, linetype = period)) +
  geom_ribbon(aes(
    ymin = lower, 
    ymax = upper,
    fill = condition,
    group = interaction(condition, period)
  ), 
  alpha = 0.2,
  color = NA
  ) +
  geom_line(aes(y = PF_torque), size = 1) +
  geom_hline(yintercept = 0) +
  scale_x_continuous(labels = NULL) +
  facet_grid(
    rows = vars(condition),
    cols = vars(stance_side)
  ) +
  scale_linetype_manual(values = c("Early Post Adapt" = "solid", "Late Baseline" = "dashed")) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(
    x = "Normalized Stance Time (0-100%)",
    y = "Ankle PF Torque (N.m/BW)",
    title = "Ankle Torque Across Conditions",
    subtitle = "Averaged Across Subjects (95% CI)",
    color = "Condition",
    fill = "Condition"
  )


ggsave(file.path(figure_directory,"bil_torque_over_time.png"))
```

## PF Impulse


```{r}

periods = c("Late Baseline", "Early Post Adapt")

PF_impulse <- mean_across_stance %>% 
  filter(period %in% periods) %>% 
  mutate(period = factor(period,levels = periods)) %>% 
  filter(variable %in% c("IPSI_ANKLE_MOMENT") & axis == "X") %>% 
  group_by(subject, period, condition, variable, normalized_time,stance_side) %>% 
  summarize(PF_torque = mean(value)) %>% 
  filter(PF_torque<0) %>%
  group_by(subject, stance_side,condition, period) %>% 
  summarize(PF_impulse = sum(PF_torque)/-100)


```
### Study 2: Unilateral


```{r, fig.width=6, fig.height=6}

plt <- PF_impulse %>% 
  ungroup() %>% 
  filter(condition %in% names(UNI_CONDITION_LABELS)) %>%  
  mutate(condition = UNI_CONDITION_LABELS[condition]) %>% 
  filter(stance_side=="left") %>% 
  ggplot(aes(x = period,y=PF_impulse, group = subject, color=subject))+
  geom_point()+
  geom_line()+
  facet_grid(~condition )+
  # scale_x_discrete(guide = guide_axis(n.dodge = 2))+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom")+
  labs(
    x = "Period",
    y = "Ankle PF Impulse (N.m.s/BW)",
    title = "Ankle PF Impulse Across Periods",
  )
plt

ggsave(file.path(figure_directory,"uni_impulse.png"))

plt+
  stat_summary(aes(group = 1), 
              fun = mean, 
              geom = "line", 
              color = "black", 
              linewidth = 1, 
              linetype = "dashed", 
              alpha = .6) +
  stat_summary(aes(group = 1), 
              fun = mean, 
              geom = "point", 
              color = "black", 
              size = 3, 
              shape = 18) +
  # Optionally add mean values as text
  geom_text(stat = "summary", 
            fun = mean,
            aes(label = sprintf("%.2f", ..y..), 
                hjust = ifelse(period=="Late Baseline", 1.5, -0.5),
                group = 1),
            color = "black", 
            vjust = -0.5, 
          
            size = 3)

ggsave(file.path(figure_directory,"uni_impulse_mean.png"))
```

### Study 3: Bilateral

```{r, fig.width=6, fig.height=6}
plt <- PF_impulse %>% 
  ungroup() %>% 
  filter(condition %in% names(BIL_CONDITION_LABELS)) %>%  
  mutate(condition = BIL_CONDITION_LABELS[condition]) %>% 
  group_by(subject,condition, period) %>% 
  summarize(PF_impulse= mean(PF_impulse)) %>%  
  ggplot(aes(x = period,y=PF_impulse, group = subject, color=subject))+
  geom_point()+
  geom_line()+
  facet_grid( ~ condition)+
  # scale_x_discrete(guide = guide_axis(n.dodge = 2))+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom")+
  labs(
    x = "Period",
    y = "Ankle PF Impulse (N.m.s/BW)",
    title = "Ankle PF Impulse Across Periods",
  )
plt

ggsave(file.path(figure_directory,"bil_impulse.png"))

plt+
  stat_summary(aes(group = 1), 
              fun = mean, 
              geom = "line", 
              color = "black", 
              linewidth = 1, 
              linetype = "dashed", 
              alpha = .6) +
  stat_summary(aes(group = 1), 
              fun = mean, 
              geom = "point", 
              color = "black", 
              size = 3, 
              shape = 18) +
  # Optionally add mean values as text
  geom_text(stat = "summary", 
            fun = mean,
            aes(label = sprintf("%.2f", ..y..), 
                hjust = ifelse(period=="Late Baseline", 1.5, -0.5),
                group = 1),
            color = "black", 
            vjust = -0.5, 
          
            size = 3)

ggsave(file.path(figure_directory,"bil_impulse_w_mean.png"))
```



```{r, fig.width=10, fig.height=6}
periods = c("Late Baseline", "Early Post Adapt")

mean_across_stance %>% 
  filter(period %in% periods) %>% 
  mutate(period = factor(period,levels = periods)) %>% 
  filter(variable %in% c("PELVIS_COM") & axis == "Z") %>%
  
  ggplot(aes(x=normalized_time,y= value, linetype=period, color=condition))+
  geom_line()+
  scale_x_continuous(labels=NULL)+
  facet_grid(subject~condition + stance_side, scales="free_y")+
  scale_linetype_manual(values=c("Early Post Adapt"="solid", "Late Baseline"="dashed")) +
  theme(legend.position="bottom")+
  labs(
    x = "Normalized Stance Time (0-100%)",
    y = "Pelvis COM Height",
    title = "Mean Pelvis Height Across Stance",
    subtitle = "Averaged Across 5 Steps",
    color = "Condition"
  )

mean_across_stance %>% 
  filter(period %in% periods) %>% 
  mutate(period = factor(period,levels = periods)) %>% 
  filter(variable %in% c("PELVIS_COM") & axis == "Z") %>% 
  group_by(period, condition, variable, normalized_time,stance_side) %>% 
  summarize(PF_torque = mean(value)) %>% 
  ggplot(aes(x=normalized_time,y= PF_torque, linetype=period, color=condition))+
  geom_line()+
  scale_x_continuous(labels=NULL)+
  facet_grid(rows=vars(condition),
             cols=vars(stance_side))+
  scale_linetype_manual(values=c("Early Post Adapt"="solid", "Late Baseline"="dashed")) +
  # theme(legend.position="bottom")+
  labs(
    x = "Normalized Stance Time (0-100%)",
    y = "Pelvis COM Height",
    title = "Mean Pelvis Height Across Stance",
    subtitle = "Averaged Across Subjects",
    color = "Condition"
  )
```

