---
title: "Bilateral PDSV to Modulate Ankle Torque and Stepping"
author: "Mac Prible"
output: html_document
---



```{r setup, include=FALSE}
library(here)
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(error = TRUE)
options(error = function() traceback(2))
```

Color reference guide here: https://sape.inf.usi.ch/quick-reference/ggplot2/colour
  
# Import Data

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(lme4)
library(cowplot) # Mac, Check out customization options
library(emmeans)

tidy_data_directory <- here("data")
figure_directory <- here("manuscripts","figures")

mean_across_stance <- 
  list.files(tidy_data_directory, pattern="*_mean_across_stance.csv") %>% 
  map_df(~read_csv2(file.path(tidy_data_directory,.)))
  
```


# Mild Data Adjustments
```{r}

## Define Conditions
BIL_CONDITION_LABELS <- c(
  "bbp" = "Fast Brake",
  "bpp" = "Fast Prop"
)

## Define Periods of Interest
pre_post_periods <- c("Late Baseline", "Early Post Adapt")
primary_periods <- c("Late Baseline", "Early Adapt" , "Late Adapt", "Early Post Adapt")
pre_late_periods <- c("Late Baseline",  "Late Adapt")


## Limit Data to Bilateral Conditions
mean_across_stance <- mean_across_stance %>% 
  filter(condition %in% names(BIL_CONDITION_LABELS)) %>% 
  select(-order)


## Basic Checks You Have Data You Want
mean_across_stance %>% group_by(variable) %>% summarize()
mean_across_stance %>% group_by(condition) %>% summarize()
```

# Belt Speed

```{r}

# filter out the swing phase from contralateral belt speed
mean_across_stance %>% 
  filter(period == "Late Adapt") %>% 
  filter(
    (variable %in% c("CONTRA_BeltSpeed", "IPSI_BeltSpeed") & axis == "X") |
    (variable %in% c("CONTRA_GRF", "IPSI_GRF") & axis == "Z")
  ) %>%
  select(-axis) %>% 
  ungroup() %>% 
  group_by(subject,  condition, period,variable, normalized_time) %>% 
  summarize(value = mean(value)) %>% 
  ungroup() %>% 
  pivot_wider(values_from = value, names_from = variable) %>% 
  mutate(CONTRA_BeltSpeed = case_when(
    CONTRA_GRF < 0.1 | normalized_time >= 30 & normalized_time <= 50 ~ NA_real_,
    TRUE ~ CONTRA_BeltSpeed
  )) %>% 
  select(-contains("_GRF")) %>% 
  pivot_longer(cols = c(CONTRA_BeltSpeed, IPSI_BeltSpeed)) %>% 
  mutate(name = factor(name, levels = c("IPSI_BeltSpeed", "CONTRA_BeltSpeed"))) %>% 
  ggplot(aes(x=normalized_time,y= value,color=name, group=subject))+
  geom_line(aes(group = interaction(subject, name)), size=0.5)+
  # scale_x_continuous(labels=NULL)+
  facet_grid(~condition, labeller = labeller(condition = BIL_CONDITION_LABELS))+
  theme_minimal()+
  theme(legend.position="bottom")+
  labs(
    x = "Normalized Stance Time (0-100%)",
    y = "Belt Speed (m/s)",
    title = "Belt Speed During Stance Phase",
    subtitle = "Average of Five Steps in Late Adaptation for Each Participant",
    color = "Side"
  )+
  scale_color_manual(
    values = c("IPSI_BeltSpeed" = "blue", "CONTRA_BeltSpeed" = "red"),
    labels = c("IPSI_BeltSpeed" = "Reference Limb", "CONTRA_BeltSpeed" = "Contralateral Limb") # Added labels for each color
  )
  
ggsave(file.path(figure_directory,"Bilateral PDSV speeds.png"))
```


# Characteristic Torque Profile

## Both Sides
```{r}

# comparison <- pre_late_periods
comparison <- pre_post_periods

mean_across_stance %>% 
  filter(period %in% comparison) %>% 
  mutate(period = factor(period,levels = comparison)) %>% 
  filter(condition %in% names(BIL_CONDITION_LABELS)) %>%  
  mutate(condition = BIL_CONDITION_LABELS[condition]) %>% 
  filter(variable %in% c("IPSI_ANKLE_MOMENT") & axis == "X") %>% 
  group_by(period, condition, variable, normalized_time, stance_side) %>% 
  summarize(
    PF_torque = mean(value),
    se = sd(value)/sqrt(n()),  # Standard error
    ci = 1.96 * se,            # 95% confidence interval
    upper = PF_torque + ci,
    lower = PF_torque - ci,
    .groups = 'drop'
  ) %>% 
  ggplot(aes(x = normalized_time, color = condition, linetype = period)) +
  geom_ribbon(aes(
    ymin = lower, 
    ymax = upper,
    fill = condition,
    group = interaction(condition, period)
  ), 
  alpha = 0.2,
  color = NA
  ) +

  geom_line(aes(y = PF_torque), size = 1) +
  geom_hline(yintercept = 0) +
  scale_x_continuous(labels = NULL) +
  facet_grid(
    rows = vars(condition),
    cols = vars(stance_side)
  ) +
  scale_linetype_manual(values = setNames(c("solid", "dashed"), comparison)) + 
    theme_minimal() +
  theme(
    legend.position = "bottom",
  ) +
  labs(
    x = "Normalized Stance Time (0-100%)",
    y = "Ankle Moment (N.m/BW)",
    title = "Ankle Torque Across Conditions",
    subtitle = "Averaged Across Subjects (95% CI)",
    color = "Condition",
    fill = "Condition"
  )
  
ggsave(file.path(figure_directory,"bil_torque_over_time.png"))
```

## Averaged Across Sides
```{r}

# comparison <- pre_late_periods
comparison <- pre_post_periods

mean_across_stance %>% 
  filter(period %in% comparison) %>% 
  mutate(period = factor(period,levels = comparison)) %>% 
  filter(condition %in% names(BIL_CONDITION_LABELS)) %>%  
  mutate(condition = BIL_CONDITION_LABELS[condition]) %>% 
  filter(variable %in% c("IPSI_ANKLE_MOMENT") & axis == "X") %>%
  # filter(variable %in% c("IPSI_KNEE_MOMENT") & axis == "X") %>%
  group_by(period, condition, variable, normalized_time) %>% 
  summarize(
    PF_torque = mean(value),
    se = sd(value)/sqrt(n()),  # Standard error
    ci = 1.96 * se,            # 95% confidence interval
    upper = PF_torque + ci,
    lower = PF_torque - ci,
    .groups = 'drop'
  ) %>% 
  ggplot(aes(x = normalized_time, color = condition, linetype = period)) +
  geom_ribbon(aes(
    ymin = lower, 
    ymax = upper,
    fill = condition,
    group = interaction(condition, period)
  ), 
  alpha = 0.2,
  color = NA
  ) +
  geom_line(aes(y = PF_torque), size = 1) +
  geom_hline(yintercept = 0) +
  scale_x_continuous(labels = NULL) +
  facet_grid(
    cols = vars(condition),
  ) +
  scale_linetype_manual(values = setNames(c("solid", "dashed"), comparison)) + 
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(
    x = "Normalized Stance Time (0-100%)",
    y = "Ankle PF Torque (N.m/BW)",
    title = "Ankle Torque Across Conditions",
    subtitle = "Averaged Across Subjects (95% CI)",
    color = "Condition",
    fill = "Condition"
  )


ggsave(file.path(figure_directory,"torque_over_time.png"))
```

# PF Impulse


Needed to de-normalize impulse with respect to time.

```{r}
## Get Stance Times
stance_times <- mean_across_stance %>% 
  filter(variable %in% c("TIME") & axis == "X") %>% 
  group_by(subject, condition, period, stance_side, normalized_time) %>% 
  summarize(time = mean(value)) %>% 
  ungroup() %>% 
  group_by(subject, condition, period, stance_side) %>%   
  summarize(start_stance = min(time),
            stop_stance = max(time)) %>% 
  ungroup() %>% 
  mutate(stance_time = stop_stance - start_stance)

PF_impulse <- mean_across_stance %>% 
  filter(period %in% pre_post_periods) %>% 
  mutate(period = factor(period,levels = pre_post_periods)) %>% 
  filter(variable %in% c("IPSI_ANKLE_MOMENT") & axis == "X") %>% 
  group_by(subject, period, condition, variable, normalized_time,stance_side) %>% 
  summarize(PF_torque = mean(value)) %>% 
  filter(PF_torque<0) %>%
  group_by(subject, stance_side,condition, period) %>% 
  summarize(PF_impulse = sum(PF_torque)/-100)
```

## Plot
```{r}
plt <- PF_impulse %>% 
  ungroup() %>% 
  mutate(condition = BIL_CONDITION_LABELS[condition]) %>% 
  group_by(subject,condition, period) %>% 
  summarize(PF_impulse= mean(PF_impulse)) %>%  
  ggplot(aes(x = period,y=PF_impulse, group = subject, color=condition))+
  geom_point()+
  geom_line()+
  facet_grid( ~ condition)+
  # scale_x_discrete(guide = guide_axis(n.dodge = 2))+
  theme_minimal()+
  theme(
        # axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")+
  labs(
    x = "Period",
    y = "PF Impulse (N.m.s/BW)",
    title = "Plantarflexor Impulse Across Stance Phase by Period",
  )

# plt
# 
# ggsave(file.path(figure_directory,"bil_impulse.png"))

plt+
  stat_summary(aes(group = 1), 
              fun = mean, 
              geom = "line", 
              color = "black", 
              linewidth = 1, 
              linetype = "dashed", 
              alpha = .6) +
  stat_summary(aes(group = 1), 
              fun = mean, 
              geom = "point", 
              color = "black", 
              size = 3, 
              shape = 18) +
  # Optionally add mean values as text
  geom_text(stat = "summary", 
            fun = mean,
            aes(label = sprintf("%.2f", ..y..), 
                hjust = ifelse(period=="Late Baseline", 1.5, -0.5),
                group = 1),
            color = "black", 
            vjust = -0.5, 
          
            size = 3)

ggsave(file.path(figure_directory,"bil_impulse_w_mean.png"))
```

## Test

```{r}
bilateral_data <- PF_impulse %>% 
  ungroup() %>% 
  mutate(condition = BIL_CONDITION_LABELS[condition]) %>% 
  group_by(subject,condition, period) %>%
  summarize(PF_impulse= mean(PF_impulse))
  
# Prepare data for lmer
bilateral_data$subject <- factor(bilateral_data$subject)
bilateral_data$condition <- factor(bilateral_data$condition)
bilateral_data$period <- factor(bilateral_data$period)

model <- lmer(PF_impulse ~ period * condition + (1|subject), 
             data = bilateral_data)


summary(model)

# Compute estimated marginal means
emm <- emmeans(model, specs = ~ period | condition)

# Pairwise comparisons of Period within each Condition
period_comparisons <- pairs(emm, simple = "period", adjust="holm")
summary(period_comparisons)
```


# Pelvis Position

```{r}
periods = c("Late Adapt", "Early Post Adapt")

pelvis_COM_data <- mean_across_stance %>% 
  mutate(condition = BIL_CONDITION_LABELS[condition]) %>% 
  filter(period %in% periods) %>% 
  mutate(period = factor(period, levels = periods)) %>% 
  filter(variable %in% c("PELVIS_COM") & axis == "Y") %>% 
  
  # negative Y is forward in treadmill frame of reference
  mutate(value = -value) %>% 
  
  group_by(period, condition, subject) %>% 
  summarize(Pelvis_COM = mean(value))
```

## Plot

```{r}
  
  
pelvis_COM_data %>% 
  ggplot(aes(x=period, y= Pelvis_COM, color=condition, group=subject)) +
  geom_line() +
  geom_point() +
  facet_grid(cols=vars(condition))+
  labs(
    x = "Period",
    y = "Pelvis COM AP Position",
    title = "Mean Pelvis CoM Position",
    subtitle = "5 steps immediately before and after the end of Adaptation",
    color = "Condition"
  ) +
  theme_minimal()+
  stat_summary(aes(group = 1), 
              fun = mean, 
              geom = "line", 
              color = "black", 
              linewidth = 1, 
              linetype = "dashed", 
              alpha = .6) +
  stat_summary(aes(group = 1), 
              fun = mean, 
              geom = "point", 
              color = "black", 
              size = 3, 
              shape = 18) +
  # Optionally add mean values as text
  geom_text(stat = "summary", 
            fun = mean,
            aes(label = sprintf("%.2f", ..y..), 
                hjust = ifelse(period=="Late Adapt", 1.5, -0.5),
                group = 1),
            color = "black", 
            vjust = -0.5, 
          
            size = 3)

```

## Test

```{r}
  
# Prepare data for lmer
pelvis_COM_data$subject <- factor(pelvis_COM_data$subject)
pelvis_COM_data$condition <- factor(pelvis_COM_data$condition)
pelvis_COM_data$period <- factor(pelvis_COM_data$period)

model <- lmer(Pelvis_COM ~ period * condition + (1|subject), 
             data = pelvis_COM_data)


summary(model)

# Compute estimated marginal means
emm <- emmeans(model, specs = ~ period | condition)

# Pairwise comparisons of Period within each Condition
period_comparisons <- pairs(emm, simple = "period", adjust="holm")
summary(period_comparisons)



```

# Step Length

```{r}
step_length_data <- mean_across_stance %>% 
  filter(normalized_time==1) %>% 
  filter(axis =='Y') %>% 
  filter(variable %in% c("IPSI_HEEL", "CONTRA_HEEL", "PELVIS_COM")) %>% 
  filter(period %in% primary_periods) %>% 
  mutate(period = factor(period, levels=primary_periods)) %>% 
  
  # forward is positive
  mutate(value = -value) %>% 
  
  pivot_wider(names_from = variable) %>% 
  mutate(condition = BIL_CONDITION_LABELS[condition]) %>% 
  mutate(step_length = IPSI_HEEL - CONTRA_HEEL,
         anterior_step_length = IPSI_HEEL - PELVIS_COM,
         posterior_step_length = PELVIS_COM - CONTRA_HEEL) %>% 
  group_by(subject, condition, period) %>% 
  summarize(step_length = mean(step_length),
            anterior_step_length = mean(anterior_step_length),
            posterior_step_length = mean(posterior_step_length)) %>% 
  pivot_longer(cols=c(step_length, anterior_step_length,posterior_step_length))
```

## Plot
```{r}

step_length_data %>% 
  filter(period %in% pre_post_periods) %>% 
  ggplot(aes(x = period, y = value, color=condition))+
  geom_point()+
  facet_grid(cols = vars(condition),
             rows = vars(name),
             scales="free_y"
             )+
  
  theme_minimal()+
  labs(
    title = "Step Length Immediately Before and After End of Adaptation"
    )+
  theme(legend.position="none")+
  stat_summary(aes(group = 1), 
              fun = mean, 
              geom = "line", 
              color = "black", 
              linewidth = 1, 
              linetype = "dashed", 
              alpha = .6) +
  stat_summary(aes(group = 1), 
              fun = mean, 
              geom = "point", 
              color = "black", 
              size = 3, 
              shape = 18) +
  # Optionally add mean values as text
  geom_text(stat = "summary", 
            fun = mean,
            aes(label = sprintf("%.2f", ..y..), 
                hjust = ifelse(period=="Late Baseline", 1.5, -0.5),
                group = 1),
            color = "black", 
            vjust = -0.5, 
          
            size = 3)

```


## Test

```{r}
  
# Prepare data for lmer
step_length_data$subject <- factor(step_length_data$subject)
step_length_data$condition <- factor(step_length_data$condition)
step_length_data$period <- factor(step_length_data$period)

wide_step_length_data <- step_length_data %>% 
  filter(period %in% pre_post_periods) %>% 
  pivot_wider()

model <- lmer(posterior_step_length ~ period * condition + (1|subject), 
             data = wide_step_length_data)


summary(model)

# Compute estimated marginal means
emm <- emmeans(model, specs = ~ period | condition)

# Pairwise comparisons of Period within each Condition
period_comparisons <- pairs(emm, simple = "period", adjust="holm")
summary(period_comparisons)



```